Update util.cpp
Added (const char*) at line 737 due to:
```
../util.cpp:737:9: error: call to member function 'append' is ambiguous
    out.append(dsdtbuf, newDSDTsize);
```